### ISSUE TITLE
# 请求/easy2007下载的excel文件无法打开，麻烦进行查看

### ISSUE THREAD

**Issue by dongma** [aStudyMachine/easyexcel-utils#2]
![图片](https://user-images.githubusercontent.com/24204526/76201455-3b3b9680-622e-11ea-8f1c-197b283d44d4.png)

**Comment by aStudyMachine** [comment]
excel 参数的 data 是设为null 了吗? 如果没有数据的话 , 需要设置为空集合 . 这个是官方库的问题 , 你可以去提个issue

**Comment by dongma** [comment]
这个问题我这边已经处理，是由于excel 版本导致的（office 2016），在高版本office中会出现空白数据页的问题，可以通过在windows注册表中设置系统参数进行修改，很谢谢您的回复。
